### ISSUE TITLE
Is onlyoffice-alfresco compatible with ACS 7.1.0?

### ISSUE THREAD

**Issue by fguariba** [ONLYOFFICE/onlyoffice-alfresco#127]
Hi,
I would like to know if this plug-in is compatible also with Alfresco Content Services 7.1.0.
If not, I would like to know if a compatible version will be launched on the next months.

Thanks and best regards,
Francisco

**Comment by LinneyS** [comment]
Hi @fguariba 
Yes, plugin compatible with 7.1 version

**Comment by fredericmazzini** [comment]
Hi @LinneyS,

On Alfresco 7.1 it misses a library 

> alfresco              |         at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
alfresco              |         at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
alfresco              |         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
alfresco              |         at java.base/java.lang.Thread.run(Thread.java:829)
alfresco              | Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/exception/ExceptionUtils
alfresco              |         at com.parashift.onlyoffice.CallBack.updateNode(CallBack.java:282)
alfresco              |         at com.parashift.onlyoffice.CallBack.access$100(CallBack.java:49)
alfresco              |         at com.parashift.onlyoffice.CallBack$ProccessRequestCallback.execute(CallBack.java:212)
alfresco              |         at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:450)
