### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by sergefedorow** [ONLYOFFICE/onlyoffice-alfresco#14]
I made Ukrainian translation. But I can't make pull request. Files are attached.
[ukraine.zip](https://github.com/ONLYOFFICE/onlyoffice-alfresco/files/3652620/ukraine.zip)

**Comment by alexandervnuchkov** [comment]
Thank you very much for your contribution! We will add the translation to one of the next releases. If you want to participate in more translations of ONLYOFFICE products, feel free to contact us using the documentation@onlyoffice.com email address, so that we could provide the access to our translation system and you could add new or correct the existing ONLYOFFICE translations to Ukrainian.
