### ISSUE TITLE
Enhancements for saving documents into Alfresco

### ISSUE THREAD

**Issue by jmoest** [ONLYOFFICE/onlyoffice-alfresco#23]
Hello,
When User1 co-edit a document into OnlyOffice, he must wait that User2 will close the page before he can see his modification in Alfresco.
Can we imagine that when a document is edit into OnlyOffice, a new version is created into Alfresco and the document is saved in this version every 10 sec until editors finish the session?
Thank you
Jonathan

**Comment by Eloncase** [comment]
Hello,
We have a feature called [Force Save](https://api.onlyoffice.com/editors/save#forcesave). Document can be saved either by pressing `Save` button or by configuring the `Document Server` to initialize force save by set intervals.

This feature is not currently supported by Alfresco connector due to technical difficulties. We'll try to implement it in the near future.

**Comment by sergefedorow** [comment]
This issue solves by using ONLYOFFICE as preview engine. So user2 can see changers online. I hope some day preview will be back from original parashift connector. I allredy add preview check box on settings page in my fork, but unfortunate have no time and have pure experience to finish this job yet.
