### ISSUE TITLE
Connector compatibility

### ISSUE THREAD

**Issue by iwkse** [ONLYOFFICE/onlyoffice-alfresco#64]
Hi,
in the documentation page I find this:

The ONLYOFFICE connector is available for Alfresco v.5.2 - 6.1.

But I can't find information about alfresco 5.2

It's the same module of this repository? It works both for 6.x and 5.2?
In the README page I see it's tested with alfresco 6.x

Is the 5.2 connector the old one? cetra3 fork?

Please can you make it clearer

thanks!

**Comment by alexanderonlyoffice** [comment]
@iwkse, please note that since the version 2.0 of the ONLYOFFICE Connector for Alfresco we got over to Alfresco SDK 3.0 and according to the official documentation for Alfresco under this link https://docs.alfresco.com/5.2/references/sdk-whats-new.html#sdk-whats-new__2 it is supported by version 5.2. Unfortunately, we did not test it, as it is a pretty old version.
