### ISSUE TITLE
I am not able to configure alfresco to access onlyoffice when alfresco is in https.

### ISSUE THREAD

**Issue by andremmoraes** [ONLYOFFICE/onlyoffice-alfresco#76]
When I start alfresco in http I can configure it normally and it accesses the onlyoffice server which is also in http, but when I start alfresco in https it reports two types of errors and is unable to access the onlyoffice:

1st error: alfresco in https and onlyoffice in http gives the error "Error when trying to check ConvertService"
2nd error: alfresco and onlyoffice in https gives the error "ONLYOFFICE cannot be reached"

I tried it with onlyoffice-alfresco 4.2.0, 4.2.1 and 4.3.0.

For alfresco I'm using: https://github.com/Alfresco/alfresco-docker-installer/ in version 6.2

For onlyoffice I'm using the tutorial https://porter.io/github.com/ONLYOFFICE/Docker-CommunityServer to generate and configure the documentserver for https

could someone help me with that

**Comment by alexanderonlyoffice** [comment]
@andremmoraes, please specify some additional information about your environment and the issue: 

1. OS of the server where ONLYOFFICE is installed;
2. Its installation type (Docker, DEB/RPM or EXE);
3. Send me the command output depending on the OS and installation type of the product:

Docker: `sudo docker ps`
DEB: `apt list --installed | grep onlyoffice`
RPM: `yum list installed | grep onlyoffice` 

4. Please send me the link to the installation guide you used to deploy Document Server.

Please note that if Alfresco uses HTTPS, Document Server must also use HTTPS, otherwise there will be a Mixed Content issue.  

> For onlyoffice I'm using the tutorial https://porter.io/github.com/ONLYOFFICE/Docker-CommunityServer to generate and configure the documentserver for https

Please also note that this is the guide for the Community Server installation. You need to use installation article for the Document Server https://helpcenter.onlyoffice.com/installation/docs-community-index.aspx.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
